version: '3'

services:
  web:
    build: .
    command:  sh -c "cd ProposedSolution && ls && python manage.py filldatabase && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code

    ports:
      - "8000:8000"
