# Generated by Django 4.2.2 on 2023-11-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ind_Card', models.FloatField()),
                ('Epoch', models.CharField(max_length=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Dado_Pulm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ind_Pulm', models.FloatField()),
                ('Epoch', models.CharField(max_length=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
