# Generated by Django 4.2.2 on 2023-11-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_alter_dado_car_cpf_alter_paciente_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado_pulm',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
