# Generated by Django 4.2.2 on 2023-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_dado_car_data_dado_pulm_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado_car',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dado_pulm',
            name='data',
        ),
        migrations.AlterField(
            model_name='dado_car',
            name='Epoch',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='dado_pulm',
            name='Epoch',
            field=models.CharField(max_length=19),
        ),
    ]
