# Generated by Django 4.2.3 on 2023-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_alter_dado_car_options_alter_dado_pulm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado_car',
            name='Epoch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dado_pulm',
            name='Epoch',
            field=models.IntegerField(),
        ),
    ]
