# Generated by Django 4.2.2 on 2023-11-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_dado_car_dado_pulm_delete_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado_car',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.CharField(max_length=3),
        ),
    ]
