# Generated by Django 4.2.2 on 2023-11-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_alter_dado_pulm_cpf_alter_paciente_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado_car',
            name='data',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado_pulm',
            name='data',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
