# Generated by Django 4.2.2 on 2023-11-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_remove_dado_car_data_remove_dado_pulm_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado_car',
            name='Epoch',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dado_pulm',
            name='Epoch',
            field=models.DateTimeField(),
        ),
    ]
