# Generated by Django 4.2.2 on 2023-11-18 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_alter_dado_car_epoch_alter_dado_pulm_epoch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dado_car',
            options={'ordering': ['-Epoch']},
        ),
        migrations.AlterModelOptions(
            name='dado_pulm',
            options={'ordering': ['-Epoch']},
        ),
        migrations.AlterField(
            model_name='dado_car',
            name='Epoch',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dado_pulm',
            name='Epoch',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
