# Generated by Django 4.2.3 on 2023-11-18 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0009_alter_dado_car_epoch_alter_dado_pulm_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado_car',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dado_pulm',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
